# config.toml

[general]
email = "tucorreo@example.com"
showWarningOnDirectExecution = false

[server]
enableCORS = false
headless = true
port = 8501
maxUploadSize = 200

[runner]
command = ["streamlit"]

[logger]
level = "info"

[client]
caching = false

[theme]
base = "light"
primaryColor = "#522DB2"
backgroundColor = "#F0F2F6"

# https://docs.streamlit.io/